### PR TITLE
Fix object upload filepath in Windows

### PR DESCRIPTION
**Pull request by albisserAdrian**
Check for win32 platform and if so strip the leading / from filepath.

### CODE REVIEW

**Comment by petrbroz** [comment]
Thank you for the heads up @albisserAdrian. I had already fixed the issue in _master_ branch (using `.fsPath` instead of `.path` on the [Uri](https://code.visualstudio.com/api/references/vscode-api#Uri) object) but the fix didn't make it back to the _develop_ branch. I have just merged the fix into _develop_ as well so this PR should not be needed anymore.

**Comment by albisserAdrian** [comment]
Sorry I didn’t check the master branch. The extension wasn’t working for me so it was just a quick fix, don’t know if it is the proper way of doing it. Where does fsPath come from, can’t find any reference to it?

**Comment by petrbroz** [comment]
No, it was my fault. I forgot to bring the fix into `develop`, and also I accidentally built the last vscode extension package from `develop` instead of `master`, so the fix was not available in production. This should all be fixed now in version 0.13.1.

`fsPath` is a property of the `Uri` class. Quoting from https://code.visualstudio.com/api/references/vscode-api#Uri:
> The string representing the corresponding file system path of this Uri.

**Comment by albisserAdrian** [comment]
Haha, no worries. I was wondering where fsPath was coming from even google didn’t show anything but I figured it out with your link to the uri class docs. 
With the branches the same thing always happened to me, so now I just use master as the develop branch and have a separate one for production. 
Anyway, thanks for this amazing extension!

**Pull request closed without merging**
